### ISSUE TITLE
Feature: A new floating header bar

### ISSUE THREAD

**Issue by tamalCodes** [ngoworldcommunity/NGOWorld#1217]
### Description

- It must be responsive for mobiles as well as the desktop version
- The design can be found below it will be best to follow the design as accurately as possible
- If needed we can integrate libraries like framework motion to make the animations much smoother else continue with the vanilla css that we are using
desktop version

### Proposed Solution

Check the figma design [here](https://www.figma.com/file/YWCRAcY0PnFrP3F7Li5i0n/Milan?type=design&node-id=0-1&mode=design&t=7FovPBpGzWOJyv4I-0) and prototype [here](https://www.figma.com/proto/YWCRAcY0PnFrP3F7Li5i0n/Milan?type=design&node-id=561-12439&t=7FovPBpGzWOJyv4I-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=561%3A12439&show-proto-sidebar=1) to see how the animation looks like

### Screenshots

![image](https://github.com/milancommunity/Milan/assets/72851613/ca2e45b8-3ff3-4a8c-9fbd-2d2cbf98ed39)
![image](https://github.com/milancommunity/Milan/assets/72851613/406fcdef-e69f-4ff8-bc8a-1af4a553d622)

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am participating in JWOC
- [ ] I am participating in IWOC
- [ ] I am willing to work on this issue (blank for no)

**Comment by riteshshukladev** [comment]
Hey @tamalCodes, would love to add this animation, kindly assign

**Comment by tamalCodes** [comment]
Hi @riteshshukladev , please go ahead with it !


## 📑 Checklist in case you missed something

- [Local project setup, .env](https://github.com/MilanCommunity/Milan#1%EF%B8%8F-setting-up-the-project-locally) for the frontend.
- [Contributing guidelines](https://github.com/MilanCommunity/Milan#2%EF%B8%8F-contributing-guidelines--more) to be followed.


Please maintain structure, use conventional pull request titles, and avoid spam to avoid closure or bans.

**Comment by riteshshukladev** [comment]
hey @tamalCodes, need your help ,as i'm facing an weird type of issue like after clonning the codebase and intallling the required dependencies . when i starts the development server and makes some changes in the codebase the changes doesn't get reflected in the UI and in the terminal of my editor.

Rather,it throws an text like this,` [BABEL] Note: The code generator has deoptimised the styling of C:\Users\Ritesh\OneDrive\Documents\Milan\src\assets\pictures\Banner\MilanBuild.svg as it exceeds the max of 500KB.`, (that is actually the build file).

To solve this issue early on i , asked chatGPT why the changes doesn't get reflected in the UI and passed this message as well, it gave me a resposne that , HMR(Hot Module Replacement) that allows developers to see their changes in the browser without needing a full page reload in web development servers, such as Webpack. 
The message you're seeing in your command line, regarding Babel deoptimizing the styling of a specific SVG file due to its size exceeding the maximum limit of 500KB, is indeed relevant and could be contributing to the issues you're experiencing. This message indicates that the SVG file is unusually large for a web asset, which might not only affect the build optimization process but could also have implications for hot module replacement (HMR) and the overall performance of your development server.  

please help!!

**Comment by tamalCodes** [comment]
That is not an error, the thing you get from Babel is a warning, everything else should work fine. Can you check the console to see? Also can you give me a screen recording using any free software so that I can see too ?
