### ISSUE TITLE
Develop Responsive and Interactive Contact Us Form 

### ISSUE THREAD

**Issue by Wadgaonkarprathameshdeepak** [ngoworldcommunity/NGOWorld#1220]
### What would you like to share?

I will create the contact us form by creating a responsive design that seamlessly adjusts to different screen sizes and interactive user interfaces.
![Screenshot 2024-02-20 113941](https://github.com/milancommunity/Milan/assets/95523666/e05cca88-532a-4aed-a0c2-cfbbe0c5ed74)

### 🥦 Browser

Google Chrome

### Checklist ✅

- [X] I checked and didn't find similar [issue](https://github.com/MilanCommunity/Milan/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/MilanCommunity/Milan/blob/main/CONTRIBUTING.md)
- [X] I am participating in JWOC
- [ ] I am participating in IWOC
- [X] I am willing to work on this issue (blank for no)

**Comment by tamalCodes** [comment]
That is an amazing feature idea, from next time raise an issue under the `feature` section !

- Okay so we have a contact form already in place, if you go to the footer and click on Contact Us a modal Opens which was initially used for this very same purpose.
- However, we would like to modify that form itself so that everything is clean neat follows our theme and also is automated to an extent


## Here is what I would like to do with this issue

- First of all, I would like to modify our current Contact Us form to be much more clean and neat and also follow the UI standards of our website such as font size and stylings
- I am also not sure but we might lack responsiveness in some cases so it is better that we fix this next slide
- Lastly, all the data must be properly sent to API when the button is hit.

**Comment by Wadgaonkarprathameshdeepak** [comment]
@tamalCodes Ok

**Comment by tamalCodes** [comment]
That's awesome, do let me know if you need any help from my side. I'd love to have this issue done as soon as possible in order to roll out these changes !

**Comment by Charan2409** [comment]
Hi @tamalCodes I would like to contribute to this , if needed any help on this please let me know

**Comment by tamalCodes** [comment]
Hi @Charan2409 thankyou for raising a concern - let me wait another day or two  - if I get no reply from the owner of this issue  - I'll assign you this.

**Comment by tamalCodes** [comment]
# Let's catch up 🙋🏻‍♂️
Hi @Wadgaonkarprathameshdeepak , it has been a while since we last had a conversation so I wanted to know if you are still working on this. Please drop a reply shortly so that we know you are active, feel free to convey any problem you face in the comments, or mail me at milanhub.org@gmail.com

**Comment by Wadgaonkarprathameshdeepak** [comment]
Hii @tamalCodes when I create a pull request then this kind of happen that reason i will not create a pull request
![image](https://github.com/milancommunity/Milan/assets/95523666/20a3795f-b7d4-4d66-8b57-5779c814b6f6)

**Comment by tamalCodes** [comment]
Make sure you make a PR from YOUR REPO/YOUR BRANCH to  `Milan community/Milan` 's  REPO/BRANCH. Often we end up making PR to our repo.

If the issue persists, try and provide me with a detailed explanation for the same / screen record.
